version: "3.7"
services:
  database:
    image: mongo:4.2
    container_name: synvia_database
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONG_INITDB_DATABASE: ${DB_DATABASE}
    command: --auth
  # api:
  #   build: .
  #   container_name: synvia-api
  #   restart: always
  #   depends_on:
  #     - database
  #   ports:
  #     - ${PORT}:${PORT}
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  # working_dir: /usr/src/app
  # env_file:
  #   - .env
  # entrypoint: ["/bin/bash", "./start.sh"]
  # logging:
  #   driver: "json-file"
  #   options:
  #     max-size: "10m"
  #     max-file: "5"
